### ISSUE TITLE
NoClassDef found for io.realm.internal.SharedGroup class

### ISSUE THREAD

**Issue by ojhariddhish** [uPhyca/stetho-realm#34] opened 2016-09-30 10:36 UTC
Realm 2.0.0 Update may have removed this class. Unable to use this library to check the Realm database. 

This is the stack trace: 
ERR: stack=java.lang.NoClassDefFoundError: Failed resolution of: Lio/realm/internal/SharedGroup;
                                                             at com.uphyca.stetho_realm.RealmPeerManager.openSharedGroupForImplicitTransactions(RealmPeerManager.java:145)
                                                             at com.uphyca.stetho_realm.RealmPeerManager.openSharedGroupForImplicitTransactions(RealmPeerManager.java:134)
                                                             at com.uphyca.stetho_realm.RealmPeerManager.getDatabaseTableNames(RealmPeerManager.java:57)
                                                             at com.uphyca.stetho_realm.Database.getDatabaseTableNames(Database.java:125)
                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                             at com.facebook.stetho.inspector.MethodDispatcher$MethodDispatchHelper.invoke(MethodDispatcher.java:96)
                                                             at com.facebook.stetho.inspector.MethodDispatcher.dispatch(MethodDispatcher.java:67)
                                                             at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteRequest(ChromeDevtoolsServer.java:129)
                                                             at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteMessage(ChromeDevtoolsServer.java:111)
                                                             at com.facebook.stetho.inspector.ChromeDevtoolsServer.onMessage(ChromeDevtoolsServer.java:87)
                                                             at com.facebook.stetho.websocket.WebSocketSession$1.handleTextFrame(WebSocketSession.java:176)
                                                             at com.facebook.stetho.websocket.WebSocketSession$1.onCompleteFrame(WebSocketSession.java:136)
                                                             at com.facebook.stetho.websocket.ReadHandler.readLoop(ReadHandler.java:44)
                                                             at com.facebook.stetho.websocket.WebSocketSession.handle(WebSocketSession.java:45)
                                                             at com.facebook.stetho.websocket.WebSocketHandler.doUpgrade(WebSocketHandler.java:117)
                                                             at com.facebook.stetho.websocket.WebSocketHandler.handleRequest(WebSocketHandler.java:83)
                                                             at com.facebook.stetho.server.http.LightHttpServer.dispatchToHandler(LightHttpServer.java:84)
                                                             at com.facebook.stetho.server.http.LightHttpServer.serve(LightHttpServer.java:61)
                                                             at com.facebook.stetho.inspector.DevtoolsSocketHandler.onAccepted(DevtoolsSocketHandler.java:52)
                                                             at com.facebook.stetho.server.ProtocolDetectingSocketHandler.onSecured(ProtocolDetectingSocketHandler.java:63)
                                                             at com.facebook.stetho.server.SecureSocketHandler.onAccepted(SecureSocketHandler.java:33)
                                                             at com.facebook.stetho.server.LazySocketHandler.onAccepted(LazySocketHandler.java:36)
                                                             at com.facebook.stetho.server.LocalSocketServer$WorkerThread.run(LocalSocketServer.java:167)
                                                          Caused by: java.lang.ClassNotFoundException: Didn't find class "io.realm.internal.SharedGroup" on path

**Comment by miroslavign** [comment] 2016-10-02 19:36
+1 same here

**Comment by miroslavign** [comment] 2016-10-02 19:37
#31  #34 all same issues

**Comment by ojhariddhish** [comment] 2016-10-03 07:31
Yes, i guess this one should be closed or merged with #31.

**Comment by zaki50** [comment] 2016-10-03 08:52
Yes, it seems duplicate of #31.
I'm working on this now.

I'll close this as duplicate.

**Closed as completed by zaki50** 2016-10-03 08:52 UTC
Labels: duplicate
